AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  
Layout/EndOfLine:
  Enabled: false
  EnforcedStyle: lf
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/MethodLength:
  Max: 12
